name: Deploy

on:
  push:
    branches:
      - main
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared-types
        run: pnpm --filter shared-types build

      - name: Generate Prisma client (user-service)
        run: pnpm --filter user-service db:generate
        env:
          USER_SERVICE_DATABASE_URL: ${{ secrets.USER_SERVICE_DATABASE_URL }}

      - name: Build user-service Lambda
        run: pnpm --filter user-service build:lambda

      - name: Generate Prisma client (job-service)
        run: pnpm --filter job-service db:generate
        env:
          JOB_SERVICE_DATABASE_URL: ${{ secrets.JOB_SERVICE_DATABASE_URL }}

      - name: Build job-service Lambda
        run: pnpm --filter job-service build:lambda

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CDK stack
        run: pnpm --filter infra run deploy
        env:
          JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
          INTERNAL_SERVICE_SECRET: ${{ secrets.INTERNAL_SERVICE_SECRET }}
          USER_SERVICE_DATABASE_URL: ${{ secrets.USER_SERVICE_DATABASE_URL }}
          JOB_SERVICE_DATABASE_URL: ${{ secrets.JOB_SERVICE_DATABASE_URL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
